/** Auto-generated by scripts/import-tarot-dataset.mjs — do not edit manually */
import { createArcanaArtwork } from "../lib/artwork";
import type { MinorTarotCard } from "../types/tarot";

const rawMinorCards = [
  {
    "id": "page-of-wands",
    "nameShort": "wapa",
    "number": 11,
    "rank": "page",
    "suit": "wands",
    "name": "Page of Wands",
    "meaningUp": "Dark young man, faithful, a lover, an envoy, a postman. Beside a man, he will bear favourable testimony concerning him. A dangerous rival, if followed by the Page of Cups. Has the chief qualities of his suit. He may signify family intelligence.",
    "meaningRev": "Anecdotes, announcements, evil news. Also indecision and the instability which accompanies it.",
    "description": "In a scene similar to the former, a young man stands in the act of proclamation. He is unknown but faithful, and his tidings are strange.",
    "artwork": {
      "symbol": "PA",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "knight-of-wands",
    "nameShort": "wakn",
    "number": 12,
    "rank": "knight",
    "suit": "wands",
    "name": "Knight of Wands",
    "meaningUp": "Departure, absence, flight, emigration. A dark young man, friendly. Change of residence.",
    "meaningRev": "Rupture, division, interruption, discord.",
    "description": "He is shewn as if upon a journey, armed with a short wand, and although mailed is not on a warlike errand. He is passing mounds or pyramids. The motion of the horse is a key to the character of its rider, and suggests th",
    "artwork": {
      "symbol": "KN",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "queen-of-wands",
    "nameShort": "waqu",
    "number": 13,
    "rank": "queen",
    "suit": "wands",
    "name": "Queen of Wands",
    "meaningUp": "A dark woman, countrywoman, friendly, chaste, loving, honourable. If the card beside her signifies a man, she is well disposed towards him; if a woman, she is interested in the Querent. Also, love of money, or a certain success in business.",
    "meaningRev": "Good, economical, obliging, serviceable. Signifies also--but in certain positions and in the neighbourhood of other cards tending in such directions--opposition, jealousy, even deceit and infidelity.",
    "description": "The Wands throughout this suit are always in leaf, as it is a suit of life and animation. Emotionally and otherwise, the Queen's personality corresponds to that of the King, but is more magnetic.",
    "artwork": {
      "symbol": "QU",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "king-of-wands",
    "nameShort": "waki",
    "number": 14,
    "rank": "king",
    "suit": "wands",
    "name": "King of Wands",
    "meaningUp": "Dark man, friendly, countryman, generally married, honest and conscientious. The card always signifies honesty, and may mean news concerning an unexpected heritage to fall in before very long.",
    "meaningRev": "Good, but severe; austere, yet tolerant.",
    "description": "The physical and emotional nature to which this card is attributed is dark, ardent, lithe, animated, impassioned, noble. The King uplifts a flowering wand, and wears, like his three correspondences in the remaining suits",
    "artwork": {
      "symbol": "KI",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "ace-of-wands",
    "nameShort": "waac",
    "number": 1,
    "rank": "ace",
    "suit": "wands",
    "name": "Ace of Wands",
    "meaningUp": "Creation, invention, enterprise, the powers which result in these; principle, beginning, source; birth, family, origin, and in a sense the virility which is behind them; the starting point of enterprises; according to another account, money, fortune, inheritance.",
    "meaningRev": "Fall, decadence, ruin, perdition, to perish also a certain clouded joy.",
    "description": "A hand issuing from a cloud grasps a stout wand or club.",
    "artwork": {
      "symbol": "AC",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "two-of-wands",
    "nameShort": "wa02",
    "number": null,
    "rank": "two",
    "suit": "wands",
    "name": "Two of Wands",
    "meaningUp": "Between the alternative readings there is no marriage possible; on the one hand, riches, fortune, magnificence; on the other, physical suffering, disease, chagrin, sadness, mortification. The design gives one suggestion; here is a lord overlooking his dominion and alternately contemplating a globe; it looks like the malady, the mortification, the sadness of Alexander amidst the grandeur of this world's wealth.",
    "meaningRev": "Surprise, wonder, enchantment, emotion, trouble, fear.",
    "description": "A tall man looks from a battlemented roof over sea and shore; he holds a globe in his right hand, while a staff in his left rests on the battlement; another is fixed in a ring. The Rose and Cross and Lily should be notic",
    "artwork": {
      "symbol": "TW",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "three-of-wands",
    "nameShort": "wa03",
    "number": null,
    "rank": "three",
    "suit": "wands",
    "name": "Three of Wands",
    "meaningUp": "He symbolizes established strength, enterprise, effort, trade, commerce, discovery; those are his ships, bearing his merchandise, which are sailing over the sea. The card also signifies able co-operation in business, as if the successful merchant prince were looking from his side towards yours with a view to help you.",
    "meaningRev": "The end of troubles, suspension or cessation of adversity, toil and disappointment.",
    "description": "A calm, stately personage, with his back turned, looking from a cliff's edge at ships passing over the sea. Three staves are planted in the ground, and he leans slightly on one of them.",
    "artwork": {
      "symbol": "TH",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "four-of-wands",
    "nameShort": "wa04",
    "number": null,
    "rank": "four",
    "suit": "wands",
    "name": "Four of Wands",
    "meaningUp": "They are for once almost on the surface--country life, haven of refuge, a species of domestic harvest-home, repose, concord, harmony, prosperity, peace, and the perfected work of these.",
    "meaningRev": "The meaning remains unaltered; it is prosperity, increase, felicity, beauty, embellishment.",
    "description": "From the four great staves planted in the foreground there is a great garland suspended; two female figures uplift nosegays; at their side is a bridge over a moat, leading to an old manorial house.",
    "artwork": {
      "symbol": "FO",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "five-of-wands",
    "nameShort": "wa05",
    "number": null,
    "rank": "five",
    "suit": "wands",
    "name": "Five of Wands",
    "meaningUp": "Imitation, as, for example, sham fight, but also the strenuous competition and struggle of the search after riches and fortune. In this sense it connects with the battle of life. Hence some attributions say that it is a card of gold, gain, opulence.",
    "meaningRev": "Litigation, disputes, trickery, contradiction.",
    "description": "A posse of youths, who are brandishing staves, as if in sport or strife. It is mimic warfare, and hereto correspond the",
    "artwork": {
      "symbol": "FI",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "six-of-wands",
    "nameShort": "wa06",
    "number": null,
    "rank": "six",
    "suit": "wands",
    "name": "Six of Wands",
    "meaningUp": "The card has been so designed that it can cover several significations; on the surface, it is a victor triumphing, but it is also great news, such as might be carried in state by the King's courier; it is expectation crowned with its own desire, the crown of hope, and so forth.",
    "meaningRev": "Apprehension, fear, as of a victorious enemy at the gate; treachery, disloyalty, as of gates being opened to the enemy; also indefinite delay.",
    "description": "A laurelled horseman bears one staff adorned with a laurel crown; footmen with staves are at his side.",
    "artwork": {
      "symbol": "SI",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "seven-of-wands",
    "nameShort": "wa07",
    "number": null,
    "rank": "seven",
    "suit": "wands",
    "name": "Seven of Wands",
    "meaningUp": "It is a card of valour, for, on the surface, six are attacking one, who has, however, the vantage position. On the intellectual plane, it signifies discussion, wordy strife; in business--negotiations, war of trade, barter, competition. It is further a card of success, for the combatant is on the top and his enemies may be unable to reach him.",
    "meaningRev": "Perplexity, embarrassments, anxiety. It is also a caution against indecision.",
    "description": "A young man on a craggy eminence brandishing a staff; six other staves are raised towards him from below.",
    "artwork": {
      "symbol": "SE",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "eight-of-wands",
    "nameShort": "wa08",
    "number": null,
    "rank": "eight",
    "suit": "wands",
    "name": "Eight of Wands",
    "meaningUp": "Activity in undertakings, the path of such activity, swiftness, as that of an express messenger; great haste, great hope, speed towards an end which promises assured felicity; generally, that which is on the move; also the arrows of love.",
    "meaningRev": "Arrows of jealousy, internal dispute, stingings of conscience, quarrels; and domestic disputes for persons who are married.",
    "description": "The card represents motion through the immovable-a flight of wands through an open country; but they draw to the term of their course. That which they signify is at hand; it may be even on the threshold.",
    "artwork": {
      "symbol": "EI",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "nine-of-wands",
    "nameShort": "wa09",
    "number": null,
    "rank": "nine",
    "suit": "wands",
    "name": "Nine of Wands",
    "meaningUp": "The card signifies strength in opposition. If attacked, the person will meet an onslaught boldly; and his build shews, that he may prove a formidable antagonist. With this main significance there are all its possible adjuncts--delay, suspension, adjournment.",
    "meaningRev": "Obstacles, adversity, calamity.",
    "description": "The figure leans upon his staff and has an expectant look, as if awaiting an enemy. Behind are eight other staves--erect, in orderly disposition, like a palisade.",
    "artwork": {
      "symbol": "NI",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "ten-of-wands",
    "nameShort": "wa10",
    "number": null,
    "rank": "ten",
    "suit": "wands",
    "name": "Ten of Wands",
    "meaningUp": "A card of many significances, and some of the readings cannot be harmonized. I set aside that which connects it with honour and good faith. The chief meaning is oppression simply, but it is also fortune, gain, any kind of success, and then it is the oppression of these things. It is also a card of false-seeming, disguise, perfidy. The place which the figure is approaching may suffer from the rods that he carries. Success is stultified if the Nine of Swords follows, and if it is a question of a lawsuit, there will be certain loss.",
    "meaningRev": "Contrarieties, difficulties, intrigues, and their analogies.",
    "description": "A man oppressed by the weight of the ten staves which he is carrying.",
    "artwork": {
      "symbol": "TE",
      "motif": "sun",
      "palette": [
        "#5c2e1a",
        "#c45c26",
        "#17110f"
      ]
    }
  },
  {
    "id": "page-of-cups",
    "nameShort": "cupa",
    "number": 11,
    "rank": "page",
    "suit": "cups",
    "name": "Page of Cups",
    "meaningUp": "Fair young man, one impelled to render service and with whom the Querent will be connected; a studious youth; news, message; application, reflection, meditation; also these things directed to business.",
    "meaningRev": "Taste, inclination, attachment, seduction, deception, artifice.",
    "description": "A fair, pleasing, somewhat effeminate page, of studious and intent aspect, contemplates a fish rising from a cup to look at him. It is the pictures of the mind taking form.",
    "artwork": {
      "symbol": "PA",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "knight-of-cups",
    "nameShort": "cukn",
    "number": 12,
    "rank": "knight",
    "suit": "cups",
    "name": "Knight of Cups",
    "meaningUp": "Arrival, approach--sometimes that of a messenger; advances, proposition, demeanour, invitation, incitement.",
    "meaningRev": "Trickery, artifice, subtlety, swindling, duplicity, fraud.",
    "description": "Graceful, but not warlike; riding quietly, wearing a winged helmet, referring to those higher graces of the imagination which sometimes characterize this card. He too is a dreamer, but the images of the side of sense hau",
    "artwork": {
      "symbol": "KN",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "queen-of-cups",
    "nameShort": "cuqu",
    "number": 13,
    "rank": "queen",
    "suit": "cups",
    "name": "Queen of Cups",
    "meaningUp": "Good, fair woman; honest, devoted woman, who will do service to the Querent; loving intelligence, and hence the gift of vision; success, happiness, pleasure; also wisdom, virtue; a perfect spouse and a good mother.",
    "meaningRev": "The accounts vary; good woman; otherwise, distinguished woman but one not to be trusted; perverse woman; vice, dishonour, depravity.",
    "description": "Beautiful, fair, dreamy--as one who sees visions in a cup. This is, however, only one of her aspects; she sees, but she also acts, and her activity feeds her dream.",
    "artwork": {
      "symbol": "QU",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "king-of-cups",
    "nameShort": "cuki",
    "number": 14,
    "rank": "king",
    "suit": "cups",
    "name": "King of Cups",
    "meaningUp": "Fair man, man of business, law, or divinity; responsible, disposed to oblige the Querent; also equity, art and science, including those who profess science, law and art; creative intelligence.",
    "meaningRev": "Dishonest, double-dealing man; roguery, exaction, injustice, vice, scandal, pillage, considerable loss.",
    "description": "He holds a short sceptre in his left hand and a great cup in his right; his throne is set upon the sea; on one side a ship is riding and on the other a dolphin is leaping. The implicit is that the Sign of the Cup natural",
    "artwork": {
      "symbol": "KI",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "ace-of-cups",
    "nameShort": "cuac",
    "number": 1,
    "rank": "ace",
    "suit": "cups",
    "name": "Ace of Cups",
    "meaningUp": "House of the true heart, joy, content, abode, nourishment, abundance, fertility; Holy Table, felicity hereof.",
    "meaningRev": "House of the false heart, mutation, instability, revolution.",
    "description": "The waters are beneath, and thereon are water-lilies; the hand issues from the cloud, holding in its palm the cup, from which four streams are pouring; a dove, bearing in its bill a cross-marked Host, descends to place t",
    "artwork": {
      "symbol": "AC",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "two-of-cups",
    "nameShort": "cu02",
    "number": null,
    "rank": "two",
    "suit": "cups",
    "name": "Two of Cups",
    "meaningUp": "Love, passion, friendship, affinity, union, concord, sympathy, the interrelation of the sexes, and--as a suggestion apart from all offices of divination--that desire which is not in Nature, but by which Nature is sanctified.",
    "meaningRev": "Lust, cupidity, jealousy, wish, desire, but the card may also give, says W., \"that desire which is not in nature, but by which nature is sanctified.\"",
    "description": "A youth and maiden are pledging one another, and above their cups rises the Caduceus of Hermes, between the great wings of which there appears a lion's head. It is a variant of a sign which is found in a few old examples",
    "artwork": {
      "symbol": "TW",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "three-of-cups",
    "nameShort": "cu03",
    "number": null,
    "rank": "three",
    "suit": "cups",
    "name": "Three of Cups",
    "meaningUp": "The conclusion of any matter in plenty, perfection and merriment; happy issue, victory, fulfilment, solace, healing,",
    "meaningRev": "Expedition, dispatch, achievement, end. It signifies also the side of excess in physical enjoyment, and the pleasures of the senses.",
    "description": "Maidens in a garden-ground with cups uplifted, as if pledging one another.",
    "artwork": {
      "symbol": "TH",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "four-of-cups",
    "nameShort": "cu04",
    "number": null,
    "rank": "four",
    "suit": "cups",
    "name": "Four of Cups",
    "meaningUp": "Weariness, disgust, aversion, imaginary vexations, as if the wine of this world had caused satiety only; another wine, as if a fairy gift, is now offered the wastrel, but he sees no consolation therein. This is also a card of blended pleasure.",
    "meaningRev": "Novelty, presage, new instruction, new relations.",
    "description": "A young man is seated under a tree and contemplates three cups set on the grass before him; an arm issuing from a cloud offers him another cup. His expression notwithstanding is one of discontent with his environment.",
    "artwork": {
      "symbol": "FO",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "five-of-cups",
    "nameShort": "cu05",
    "number": null,
    "rank": "five",
    "suit": "cups",
    "name": "Five of Cups",
    "meaningUp": "A dark, cloaked figure, looking sideways at three prone cups two others stand upright behind him; a bridge is in the background, leading to a small keep or holding. Divanatory Meanings: It is a card of loss, but something remains over; three have been taken, but two are left; it is a card of inheritance, patrimony, transmission, but not corresponding to expectations; with some interpreters it is a card of marriage, but not without bitterness or frustration.",
    "meaningRev": "News, alliances, affinity, consanguinity, ancestry, return, false projects.",
    "description": "A dark, cloaked figure, looking sideways at three prone cups two others stand upright behind him; a bridge is in the background, leading to a small keep or holding. Divanatory Meanings: It is a card of loss, but somethin",
    "artwork": {
      "symbol": "FI",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "six-of-cups",
    "nameShort": "cu06",
    "number": null,
    "rank": "six",
    "suit": "cups",
    "name": "Six of Cups",
    "meaningUp": "A card of the past and of memories, looking back, as--for example--on childhood; happiness, enjoyment, but coming rather from the past; things that have vanished. Another reading reverses this, giving new relations, new knowledge, new environment, and then the children are disporting in an unfamiliar precinct.",
    "meaningRev": "The future, renewal, that which will come to pass presently.",
    "description": "Children in an old garden, their cups filled with flowers.",
    "artwork": {
      "symbol": "SI",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "seven-of-cups",
    "nameShort": "cu07",
    "number": null,
    "rank": "seven",
    "suit": "cups",
    "name": "Seven of Cups",
    "meaningUp": "Fairy favours, images of reflection, sentiment, imagination, things seen in the glass of contemplation; some attainment in these degrees, but nothing permanent or substantial is suggested.",
    "meaningRev": "Desire, will, determination, project.",
    "description": "Strange chalices of vision, but the images are more especially those of the fantastic spirit.",
    "artwork": {
      "symbol": "SE",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "eight-of-cups",
    "nameShort": "cu08",
    "number": null,
    "rank": "eight",
    "suit": "cups",
    "name": "Eight of Cups",
    "meaningUp": "The card speaks for itself on the surface, but other readings are entirely antithetical--giving joy, mildness, timidity, honour, modesty. In practice, it is usually found that the card shews the decline of a matter, or that a matter which has been thought to be important is really of slight consequence--either for good or evil.",
    "meaningRev": "Great joy, happiness, feasting.",
    "description": "A man of dejected aspect is deserting the cups of his felicity, enterprise, undertaking or previous concern.",
    "artwork": {
      "symbol": "EI",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "nine-of-cups",
    "nameShort": "cu09",
    "number": null,
    "rank": "nine",
    "suit": "cups",
    "name": "Nine of Cups",
    "meaningUp": "Concord, contentment, physical bien-être; also victory, success, advantage; satisfaction for the Querent or person for whom the consultation is made.",
    "meaningRev": "Truth, loyalty, liberty; but the readings vary and include mistakes, imperfections, etc.",
    "description": "A goodly personage has feasted to his heart's content, and abundant refreshment of wine is on the arched counter behind him, seeming to indicate that the future is also assured. The picture offers the material side only,",
    "artwork": {
      "symbol": "NI",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "ten-of-cups",
    "nameShort": "cu10",
    "number": null,
    "rank": "ten",
    "suit": "cups",
    "name": "Ten of Cups",
    "meaningUp": "Contentment, repose of the entire heart; the perfection of that state; also perfection of human love and friendship; if with several picture-cards, a person who is taking charge of the Querent's interests; also the town, village or country inhabited by the Querent.",
    "meaningRev": "Repose of the false heart, indignation, violence.",
    "description": "Appearance of Cups in a rainbow; it is contemplated in wonder and ecstacy by a man and woman below, evidently husband and wife. His right arm is about her; his left is raised upward; she raises her right arm. The two chi",
    "artwork": {
      "symbol": "TE",
      "motif": "wave",
      "palette": [
        "#1a3a5c",
        "#3d7ab8",
        "#0e1520"
      ]
    }
  },
  {
    "id": "page-of-pentacles",
    "nameShort": "pepa",
    "number": 11,
    "rank": "page",
    "suit": "pentacles",
    "name": "Page of Pentacles",
    "meaningUp": "Application, study, scholarship, reflection another reading says news, messages and the bringer thereof; also rule, management.",
    "meaningRev": "Prodigality, dissipation, liberality, luxury; unfavourable news.",
    "description": "A youthful figure, looking intently at the pentacle which hovers over his raised hands. He moves slowly, insensible of that which is about him.",
    "artwork": {
      "symbol": "PA",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "knight-of-pentacles",
    "nameShort": "pekn",
    "number": 12,
    "rank": "knight",
    "suit": "pentacles",
    "name": "Knight of Pentacles",
    "meaningUp": "Utility, serviceableness, interest, responsibility, rectitude-all on the normal and external plane.",
    "meaningRev": "inertia, idleness, repose of that kind, stagnation; also placidity, discouragement, carelessness.",
    "description": "He rides a slow, enduring, heavy horse, to which his own aspect corresponds. He exhibits his symbol, but does not look therein.",
    "artwork": {
      "symbol": "KN",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "queen-of-pentacles",
    "nameShort": "pequ",
    "number": 13,
    "rank": "queen",
    "suit": "pentacles",
    "name": "Queen of Pentacles",
    "meaningUp": "Opulence, generosity, magnificence, security, liberty.",
    "meaningRev": "Evil, suspicion, suspense, fear, mistrust.",
    "description": "The face suggests that of a dark woman, whose qualities might be summed up in the idea of greatness of soul; she has also the serious cast of intelligence; she contemplates her symbol and may see worlds therein.",
    "artwork": {
      "symbol": "QU",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "king-of-pentacles",
    "nameShort": "peki",
    "number": 14,
    "rank": "king",
    "suit": "pentacles",
    "name": "King of Pentacles",
    "meaningUp": "Valour, realizing intelligence, business and normal intellectual aptitude, sometimes mathematical gifts and attainments of this kind; success in these paths.",
    "meaningRev": "Vice, weakness, ugliness, perversity, corruption, peril.",
    "description": "The figure calls for no special description the face is rather dark, suggesting also courage, but somewhat lethargic in tendency. The bull's head should be noted as a recurrent symbol on the throne. The sign of this suit",
    "artwork": {
      "symbol": "KI",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "ace-of-pentacles",
    "nameShort": "peac",
    "number": 1,
    "rank": "ace",
    "suit": "pentacles",
    "name": "Ace of Pentacles",
    "meaningUp": "Perfect contentment, felicity, ecstasy; also speedy intelligence; gold.",
    "meaningRev": "The evil side of wealth, bad intelligence; also great riches. In any case it shews prosperity, comfortable material conditions, but whether these are of advantage to the possessor will depend on whether the card is reversed or not.",
    "description": "A hand--issuing, as usual, from a cloud--holds up a pentacle.",
    "artwork": {
      "symbol": "AC",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "two-of-pentacles",
    "nameShort": "pe02",
    "number": null,
    "rank": "two",
    "suit": "pentacles",
    "name": "Two of Pentacles",
    "meaningUp": "On the one hand it is represented as a card of gaiety, recreation and its connexions, which is the subject of the design; but it is read also as news and messages in writing, as obstacles, agitation, trouble, embroilment.",
    "meaningRev": "Enforced gaiety, simulated enjoyment, literal sense, handwriting, composition, letters of exchange.",
    "description": "A young man, in the act of dancing, has a pentacle in either hand, and they are joined by that endless cord which is like the number 8 reversed.",
    "artwork": {
      "symbol": "TW",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "three-of-pentacles",
    "nameShort": "pe03",
    "number": null,
    "rank": "three",
    "suit": "pentacles",
    "name": "Three of Pentacles",
    "meaningUp": "Métier, trade, skilled labour; usually, however, regarded as a card of nobility, aristocracy, renown, glory.",
    "meaningRev": "Mediocrity, in work and otherwise, puerility, pettiness, weakness.",
    "description": "A sculptor at his work in a monastery. Compare the design which illustrates the Eight of Pentacles. The apprentice or amateur therein has received his reward and is now at work in earnest.",
    "artwork": {
      "symbol": "TH",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "four-of-pentacles",
    "nameShort": "pe04",
    "number": null,
    "rank": "four",
    "suit": "pentacles",
    "name": "Four of Pentacles",
    "meaningUp": "The surety of possessions, cleaving to that which one has, gift, legacy, inheritance.",
    "meaningRev": "Suspense, delay, opposition.",
    "description": "A crowned figure, having a pentacle over his crown, clasps another with hands and arms; two pentacles are under his feet. He holds to that which he has.",
    "artwork": {
      "symbol": "FO",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "five-of-pentacles",
    "nameShort": "pe05",
    "number": null,
    "rank": "five",
    "suit": "pentacles",
    "name": "Five of Pentacles",
    "meaningUp": "The card foretells material trouble above all, whether in the form illustrated--that is, destitution--or otherwise. For some cartomancists, it is a card of love and lovers-wife, husband, friend, mistress; also concordance, affinities. These alternatives cannot be harmonized.",
    "meaningRev": "Disorder, chaos, ruin, discord, profligacy.",
    "description": "Two mendicants in a snow-storm pass a lighted casement.",
    "artwork": {
      "symbol": "FI",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "six-of-pentacles",
    "nameShort": "pe06",
    "number": null,
    "rank": "six",
    "suit": "pentacles",
    "name": "Six of Pentacles",
    "meaningUp": "Presents, gifts, gratification another account says attention, vigilance now is the accepted time, present prosperity, etc.",
    "meaningRev": "Desire, cupidity, envy, jealousy, illusion.",
    "description": "A person in the guise of a merchant weighs money in a pair of scales and distributes it to the needy and distressed. It is a testimony to his own success in life, as well as to his goodness of heart.",
    "artwork": {
      "symbol": "SI",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "seven-of-pentacles",
    "nameShort": "pe07",
    "number": null,
    "rank": "seven",
    "suit": "pentacles",
    "name": "Seven of Pentacles",
    "meaningUp": "These are exceedingly contradictory; in the main, it is a card of money, business, barter; but one reading gives altercation, quarrels--and another innocence, ingenuity, purgation.",
    "meaningRev": "Cause for anxiety regarding money which it may be proposed to lend.",
    "description": "A young man, leaning on his staff, looks intently at seven pentacles attached to a clump of greenery on his right; one would say that these were his treasures and that his heart was there.",
    "artwork": {
      "symbol": "SE",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "eight-of-pentacles",
    "nameShort": "pe08",
    "number": null,
    "rank": "eight",
    "suit": "pentacles",
    "name": "Eight of Pentacles",
    "meaningUp": "Work, employment, commission, craftsmanship, skill in craft and business, perhaps in the preparatory stage.",
    "meaningRev": "Voided ambition, vanity, cupidity, exaction, usury. It may also signify the possession of skill, in the sense of the ingenious mind turned to cunning and intrigue.",
    "description": "An artist in stone at his work, which he exhibits in the form of trophies.",
    "artwork": {
      "symbol": "EI",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "nine-of-pentacles",
    "nameShort": "pe09",
    "number": null,
    "rank": "nine",
    "suit": "pentacles",
    "name": "Nine of Pentacles",
    "meaningUp": "Prudence, safety, success, accomplishment, certitude, discernment.",
    "meaningRev": "Roguery, deception, voided project, bad faith.",
    "description": "A woman, with a bird upon her wrist, stands amidst a great abundance of grapevines in the garden of a manorial house. It is a wide domain, suggesting plenty in all things. Possibly it is her own possession and testifies ",
    "artwork": {
      "symbol": "NI",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "ten-of-pentacles",
    "nameShort": "pe10",
    "number": null,
    "rank": "ten",
    "suit": "pentacles",
    "name": "Ten of Pentacles",
    "meaningUp": "Gain, riches; family matters, archives, extraction, the abode of a family.",
    "meaningRev": "Chance, fatality, loss, robbery, games of hazard; sometimes gift, dowry, pension.",
    "description": "A man and woman beneath an archway which gives entrance to a house and domain. They are accompanied by a child, who looks curiously at two dogs accosting an ancient personage seated in the foreground. The child's hand is",
    "artwork": {
      "symbol": "TE",
      "motif": "circle",
      "palette": [
        "#3d4a2a",
        "#7a8f4e",
        "#141810"
      ]
    }
  },
  {
    "id": "page-of-swords",
    "nameShort": "swpa",
    "number": 11,
    "rank": "page",
    "suit": "swords",
    "name": "Page of Swords",
    "meaningUp": "Authority, overseeing, secret service, vigilance, spying, examination, and the qualities thereto belonging.",
    "meaningRev": "More evil side of these qualities; what is unforeseen, unprepared state; sickness is also intimated.",
    "description": "A lithe, active figure holds a sword upright in both hands, while in the act of swift walking. He is passing over rugged land, and about his way the clouds are collocated wildly. He is alert and lithe, looking this way a",
    "artwork": {
      "symbol": "PA",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "knight-of-swords",
    "nameShort": "swkn",
    "number": 12,
    "rank": "knight",
    "suit": "swords",
    "name": "Knight of Swords",
    "meaningUp": "Skill, bravery, capacity, defence, address, enmity, wrath, war, destruction, opposition, resistance, ruin. There is therefore a sense in which the card signifies death, but it carries this meaning only in its proximity to other cards of fatality.",
    "meaningRev": "Imprudence, incapacity, extravagance.",
    "description": "He is riding in full course, as if scattering his enemies. In the design he is really a prototypical hero of romantic chivalry. He might almost be Galahad, whose sword is swift and sure because he is clean of heart.",
    "artwork": {
      "symbol": "KN",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "queen-of-swords",
    "nameShort": "swqu",
    "number": 13,
    "rank": "queen",
    "suit": "swords",
    "name": "Queen of Swords",
    "meaningUp": "Widowhood, female sadness and embarrassment, absence, sterility, mourning, privation, separation.",
    "meaningRev": "Malice, bigotry, artifice, prudery, bale, deceit.",
    "description": "Her right hand raises the weapon vertically and the hilt rests on an arm of her royal chair the left hand is extended, the arm raised her countenance is severe but chastened; it suggests familiarity with sorrow. It does ",
    "artwork": {
      "symbol": "QU",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "king-of-swords",
    "nameShort": "swki",
    "number": 14,
    "rank": "king",
    "suit": "swords",
    "name": "King of Swords",
    "meaningUp": "Whatsoever arises out of the idea of judgment and all its connexions-power, command, authority, militant intelligence, law, offices of the crown, and so forth.",
    "meaningRev": "Cruelty, perversity, barbarity, perfidy, evil intention.",
    "description": "He sits in judgment, holding the unsheathed sign of his suit. He recalls, of course, the conventional Symbol of justice in the Trumps Major, and he may represent this virtue, but he is rather the power of life and death,",
    "artwork": {
      "symbol": "KI",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "ace-of-swords",
    "nameShort": "swac",
    "number": 1,
    "rank": "ace",
    "suit": "swords",
    "name": "Ace of Swords",
    "meaningUp": "Triumph, the excessive degree in everything, conquest, triumph of force. It is a card of great force, in love as well as in hatred. The crown may carry a much higher significance than comes usually within the sphere of fortune-telling.",
    "meaningRev": "The same, but the results are disastrous; another account says--conception, childbirth, augmentation, multiplicity.",
    "description": "A hand issues from a cloud, grasping as word, the point of which is encircled by a crown.",
    "artwork": {
      "symbol": "AC",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "two-of-swords",
    "nameShort": "sw02",
    "number": null,
    "rank": "two",
    "suit": "swords",
    "name": "Two of Swords",
    "meaningUp": "Conformity and the equipoise which it suggests, courage, friendship, concord in a state of arms; another reading gives tenderness, affection, intimacy. The suggestion of harmony and other favourable readings must be considered in a qualified manner, as Swords generally are not symbolical of beneficent forces in human affairs.",
    "meaningRev": "Imposture, falsehood, duplicity, disloyalty.",
    "description": "A hoodwinked female figure balances two swords upon her shoulders.",
    "artwork": {
      "symbol": "TW",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "three-of-swords",
    "nameShort": "sw03",
    "number": null,
    "rank": "three",
    "suit": "swords",
    "name": "Three of Swords",
    "meaningUp": "Removal, absence, delay, division, rupture, dispersion, and all that the design signifies naturally, being too simple and obvious to call for specific enumeration.",
    "meaningRev": "Mental alienation, error, loss, distraction, disorder, confusion.",
    "description": "Three swords piercing a heart; cloud and rain behind.",
    "artwork": {
      "symbol": "TH",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "four-of-swords",
    "nameShort": "sw04",
    "number": null,
    "rank": "four",
    "suit": "swords",
    "name": "Four of Swords",
    "meaningUp": "Vigilance, retreat, solitude, hermit's repose, exile, tomb and coffin. It is these last that have suggested the design.",
    "meaningRev": "Wise administration, circumspection, economy, avarice, precaution, testament.",
    "description": "The effigy of a knight in the attitude of prayer, at full length upon his tomb.",
    "artwork": {
      "symbol": "FO",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "five-of-swords",
    "nameShort": "sw05",
    "number": null,
    "rank": "five",
    "suit": "swords",
    "name": "Five of Swords",
    "meaningUp": "Degradation, destruction, revocation, infamy, dishonour, loss, with the variants and analogues of these.",
    "meaningRev": "The same; burial and obsequies.",
    "description": "A disdainful man looks after two retreating and dejected figures. Their swords lie upon the ground. He carries two others on his left shoulder, and a third sword is in his right hand, point to earth. He is the master in ",
    "artwork": {
      "symbol": "FI",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "six-of-swords",
    "nameShort": "sw06",
    "number": null,
    "rank": "six",
    "suit": "swords",
    "name": "Six of Swords",
    "meaningUp": "Journey by water, route, way, envoy, commissionary, expedient.",
    "meaningRev": "Declaration, confession, publicity; one account says that it is a proposal of love.",
    "description": "A ferryman carrying passengers in his punt to the further shore. The course is smooth, and seeing that the freight is light, it may be noted that the work is not beyond his strength.",
    "artwork": {
      "symbol": "SI",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "seven-of-swords",
    "nameShort": "sw07",
    "number": null,
    "rank": "seven",
    "suit": "swords",
    "name": "Seven of Swords",
    "meaningUp": "Design, attempt, wish, hope, confidence; also quarrelling, a plan that may fail, annoyance. The design is uncertain in its import, because the significations are widely at variance with each other.",
    "meaningRev": "Good advice, counsel, instruction, slander, babbling.",
    "description": "A man in the act of carrying away five swords rapidly; the two others of the card remain stuck in the ground. A camp is close at hand.",
    "artwork": {
      "symbol": "SE",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "eight-of-swords",
    "nameShort": "sw08",
    "number": null,
    "rank": "eight",
    "suit": "swords",
    "name": "Eight of Swords",
    "meaningUp": "Bad news, violent chagrin, crisis, censure, power in trammels, conflict, calumny; also sickness.",
    "meaningRev": "Disquiet, difficulty, opposition, accident, treachery; what is unforeseen; fatality.",
    "description": "A woman, bound and hoodwinked, with the swords of the card about her. Yet it is rather a card of temporary durance than of irretrievable bondage.",
    "artwork": {
      "symbol": "EI",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "nine-of-swords",
    "nameShort": "sw09",
    "number": null,
    "rank": "nine",
    "suit": "swords",
    "name": "Nine of Swords",
    "meaningUp": "Death, failure, miscarriage, delay, deception, disappointment, despair.",
    "meaningRev": "Imprisonment, suspicion, doubt, reasonable fear, shame.",
    "description": "One seated on her couch in lamentation, with the swords over her. She is as one who knows no sorrow which is like unto hers. It is a card of utter desolation.",
    "artwork": {
      "symbol": "NI",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  },
  {
    "id": "ten-of-swords",
    "nameShort": "sw10",
    "number": null,
    "rank": "ten",
    "suit": "swords",
    "name": "Ten of Swords",
    "meaningUp": "Whatsoever is intimated by the design; also pain, affliction, tears, sadness, desolation. It is not especially a card of violent death.",
    "meaningRev": "Advantage, profit, success, favour, but none of these are permanent; also power and authority.",
    "description": "A prostrate figure, pierced by all the swords belonging to the card.",
    "artwork": {
      "symbol": "TE",
      "motif": "pillar",
      "palette": [
        "#3a3f4a",
        "#8a9bb0",
        "#12141a"
      ]
    }
  }
] as Array<{
  id: string;
  nameShort: string;
  number: number;
  rank: string;
  suit: "wands" | "cups" | "swords" | "pentacles";
  name: string;
  meaningUp: string;
  meaningRev: string;
  description: string;
  artwork: { symbol: string; motif: "circle" | "triangle" | "pillar" | "wave" | "sun" | "gate"; palette: [string, string, string] };
}>;

export const minorArcana: MinorTarotCard[] = rawMinorCards.map((card) => ({
  ...card,
  positiveKeywords: card.meaningUp.split(/[,;]/).map((s) => s.trim()).filter(Boolean).slice(0, 4),
  cautionKeywords: card.meaningRev.split(/[,;]/).map((s) => s.trim()).filter(Boolean).slice(0, 4),
  meanings: {
    general: card.meaningUp,
    love: card.meaningUp,
    work: card.meaningUp,
    spirituality: card.meaningUp,
    shadow: card.meaningRev,
  },
  keywords: [] as string[],
  image: createArcanaArtwork({
    name: card.name,
    number: card.number,
    artwork: card.artwork,
  }),
}));
